//This c program generates pseudo random numbers using rand and random function(Turbo C 
//compiler only). As the random numbers are generated by an algorithm used in a function
// they are pseudo random, this is the reason why pseudo word is used.

#include <stdio.h>
#include <stdlib.h>
 
int main() {
  int c, n;
 
  printf("Ten random numbers in [1,100]\n");
 
  for (c = 1; c <= 10; c++) {
    n = rand() % 100 + 1;
    printf("%d\n", n);
  }
 
  return 0;
}